project_name: talos-bootstrap
builds:
  - id: cli
    dir: ./bootstrap
    main: .
    binary: stolos-bootstrap
    env:
      - CGO_ENABLED=0
    ldflags:
      - -extldflags "-static"
      - -X main.GithubClientId={{ .Env.GITHUB_CLIENT_ID }}
      - -X main.GithubClientSecret={{ .Env.GITHUB_CLIENT_SECRET }}
      - -X main.GCPClientId={{ .Env.GCP_CLIENT_ID }}
      - -X main.GCPClientSecret={{ .Env.GCP_CLIENT_SECRET }}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
archives:
  - id: default
    format: tar.gz
    builds:
      - cli
    name_template: >-
      stolos-bootstrap_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}

release:
  prerelease: auto
