---
apiVersion: v1
kind: ConfigMap
metadata:
  name: obi-config
  namespace: monitoring
data:
  obi-config.yml: |
    trace_printer: text
    otel_traces_export:
      endpoint: http://tempo:4317
      sampler:
        name: parentbased_traceidratio
        arg: "0.1"
    routes:
      patterns:
        - /api/v1/*
        - /health
    discovery:
      instrument:
        - k8s_namespace: stolos
          k8s_deployment_name: stolos-backend
          open_ports: 8080