name: Stolos Backend CICD

on:
  push:
    branches:
      - main
    paths:
      - backend/**
  pull_request:
    branches:
      - main
    paths:
      - backend/**
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'master'

permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: backend/go.mod
          cache: true

      - name: Go vet
        run: go vet ./...

      - name: Run tests
        run: go test -race -count=1 ./tests/


  build-push-ghcr:
    needs: ci
    uses: stolos-cloud/stolos/.github/workflows/build-push-ghcr.yml@feature/backend-deployment
    with:
      container-name: stolos-backend
      branch: ${{ github.event.inputs.branch }}
      context: backend
      file: backend/Dockerfile
    secrets: inherit