name: Move issues to next iteration

on:
  workflow_dispatch:
  pull_request:

permissions:
  issues: write
  repository-projects: write

jobs:
  move-to-next-iteration:
    name: Move to next iteration
    runs-on: ubuntu-latest

    steps:
    - uses: blombard/move-to-next-iteration@master
      with:
        owner: stolos-cloud
        number: 1
        token: ${{ secrets.GITHUB_TOKEN }}
        iteration-field: Iteration
        iteration: last
        new-iteration: current
        excluded-statuses: "Done,Won't Fix"
